# Generated by Django 4.2.6 on 2023-10-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todocharts',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
