# Generated by Django 4.2.6 on 2023-10-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0002_alter_todocharts_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todocharts',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='todocharts',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
